# Generated by Django 4.1.3 on 2022-11-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number_availbale',
            new_name='number_available',
        ),
    ]
