# Generated by Django 4.1.3 on 2022-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_author_name_alter_book_author_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
