# Generated by Django 4.1.3 on 2022-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
