# Generated by Django 4.1.3 on 2022-11-09 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_date_ended_alter_booking_date_max_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 15, 23, 23, 490422)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_max_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 15, 23, 23, 490431)),
        ),
    ]
