# Generated by Django 4.1.3 on 2022-11-10 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_updated_at_alter_booking_date_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 1, 38, 21, 302305)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_max_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 1, 38, 21, 302318)),
        ),
    ]
