# Generated by Django 4.1.3 on 2022-11-10 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_date_ended_alter_booking_date_max_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 2, 0, 28, 590123)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_max_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 2, 0, 28, 590133)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rent_status',
            field=models.CharField(choices=[('TAKEN', 'Взял_а'), ('RETURNED', 'Вернул_а'), ('OWES', 'Должен_на')], default='TAKEN', max_length=10),
        ),
    ]
